### ISSUE TITLE
Building 2022.3 on Unix, Missing libxlsxwriter

### ISSUE THREAD

**Issue by shmorgan** [xLightsSequencer/xlights-build-docker#2]
Trying to build xlights 2022.3 after a clean system install, Using the docker scripts as examples to install dependencies, I'm still having issues with the libxlsxwriter library. I added scripting to download and install the library, but it seems that the Makefile for xlights is looking only in the dependency subdirectory and there is no logic in the Makefile to download and install the missing library currently.

**Comment by shmorgan** [comment]
This maybe an issue with the Makefile for xLights, so let me know and I will open a ticket there instead.

**Comment by cjd** [comment]
The docker build scripts have been updated - as have build instructions in xLights repository - so this should be resolved
